name: Dreamlabs Automation
# makes little sense, spell-checker: disable
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main
      - develop
      - factory
      - release/**
      - hotfix/**

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version:
            - '3.7'
            - '3.8'
            - '3.9'
            - '3.10'
            - '3.11'
            - '3.12'
    name: Ubuntu Python ${{ matrix.python_version }}
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: 🧳 Install Dreamlabs and dependencies
        run: |
          sudo apt-get update
          python -m pip install --no-python-version-warning --disable-pip-version-check -r requirements.txt

      - name: Run Dreamlabs Automation
        run: |
          python my_script.py --no-other-python --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads
