name: Dreamlabs Download Data
# makes little sense, spell-checker: disable
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - main
      - develop
      - factory
      - release/**
      - hotfix/**
  schedule:
    # Runs at 09:30, Monday through Friday，and Sunday
    # 北京时间+8，17点30分
    - cron: '30 9 * * 1-5'

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version:
            - '3.9'
    name: Ubuntu Python ${{ matrix.python_version }}
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies

      - name: 🧳 Install Dreamlabs and dependencies
        run: |
          sudo apt-get update
          python -m pip install --no-python-version-warning --disable-pip-version-check -r requirements.txt

      - name: Run Dreamlabs Automation【Download Data】
        run: |
          python incremental_download_data_script.py --no-other-python --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads
