name: Remote SSH and git pull
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          cd /volume1/docker/python-chromedriver/work/dreamlabs-cb
          /usr/local/bin/git pull
          cd /volume1/docker/python-chromedriver/work/dreamlabs-pairs
          /usr/local/bin/git pull
