name: Dreamlabs Automation
# makes little sense, spell-checker: disable
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - main
      - develop
      - factory
      - release/**
      - hotfix/**
  schedule:
    # 每天在国际标准时间1,2,5,6点（北京时间+8，即9,10,13,14点）运行
    - cron: '30 1,2,5,6 * * 1-5'

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version:
            - '3.9'
    name: Ubuntu Python ${{ matrix.python_version }}
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: 🧳 Install Dreamlabs and dependencies
        run: |
          sudo apt-get update
          python -m pip install --no-python-version-warning --disable-pip-version-check -r requirements.txt

      - name: Run Dreamlabs Automation【Grid Trading】
        run: |
          python grid_trading_script.py --no-other-python --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads

      - name: Run Dreamlabs Automation【Pairs Trading】
        run: |
          python hello_world_script.py --no-other-python --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads

      - name: Run Dreamlabs Automation【CB Trading】
        run: |
          python hello_world_script.py --no-other-python --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads
